version: "3.10"

services:
  flask_app:
    container_name: flask_app
    image: wisper098/flask_forum_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URI=postgresql://postgres:Ogera228@flask_db:5432/web-forum
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Ogera228
      - POSTGRES_USER=postgres
      - POSTGRES_DB=web-forum
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}